export const DEMO_STORES = {
  tiktok: {
    id: "demo-tiktok",
    tenantId: "demo",
    name: "Zuri Collections",
    slug: "zuri-collections",
    type: "tiktok" as const,
    status: "active",
    domain: "/stores/tiktok/demo-tiktok",
    theme: {
      primaryColor: "#10b981",
      accentColor: "#f97316",
      backgroundColor: "#ffffff",
      fontFamily: "plus_jakarta" as const,
      logoUrl: null,
      bannerUrl: null,
      bannerText: "LIVE NOW — Limited stock available!",
    },
    productCount: 1,
    orderCount: 14,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  social: {
    id: "demo-social",
    tenantId: "demo",
    name: "Amani Beauty",
    slug: "amani-beauty",
    type: "social" as const,
    status: "active",
    domain: "/stores/social/demo-social",
    theme: {
      primaryColor: "#10b981",
      accentColor: "#f97316",
      backgroundColor: "#faf9f7",
      fontFamily: "plus_jakarta" as const,
      logoUrl: null,
      bannerUrl: null,
      bannerText: "Free delivery on orders over KES 2,000",
    },
    productCount: 6,
    orderCount: 47,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  boutique: {
    id: "demo-boutique",
    tenantId: "demo",
    name: "Elegance Boutique",
    slug: "elegance-boutique",
    type: "boutique" as const,
    status: "active",
    domain: "/stores/boutique/demo-boutique",
    theme: {
      primaryColor: "#10b981",
      accentColor: "#f97316",
      backgroundColor: "#fafafa",
      fontFamily: "outfit" as const,
      logoUrl: null,
      bannerUrl: null,
      bannerText: "New arrivals every week — Shop the latest looks",
    },
    productCount: 12,
    orderCount: 128,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
};

export const DEMO_PRODUCTS = {
  tiktok: [
    {
      id: "tt-p1",
      storeId: "demo-tiktok",
      name: "Premium Shea Butter Gift Set",
      description:
        "100% pure organic shea butter sourced from Ghana. Deeply moisturizing for skin and hair. 3-piece set includes body butter, lip balm, and hair cream.",
      priceKes: 1500,
      originalPriceKes: 2200,
      imageUrl: null,
      images: [] as string[],
      category: "Skincare",
      stock: 23,
      featured: true,
      active: true,
      createdAt: new Date().toISOString(),
    },
  ],
  social: [
    {
      id: "so-p1",
      storeId: "demo-social",
      name: "Vitamin C Brightening Serum",
      description: "Fade dark spots and even skin tone in 4 weeks.",
      priceKes: 1800,
      originalPriceKes: 2500,
      imageUrl: null,
      images: [] as string[],
      category: "Skincare",
      stock: 45,
      featured: true,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "so-p2",
      storeId: "demo-social",
      name: "Castor Oil Hair Growth Kit",
      description: "Stimulate hair growth and reduce breakage.",
      priceKes: 950,
      originalPriceKes: 1400,
      imageUrl: null,
      images: [] as string[],
      category: "Hair Care",
      stock: 38,
      featured: true,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "so-p3",
      storeId: "demo-social",
      name: "Natural Charcoal Face Mask",
      description: "Deep cleansing mask for clear, glowing skin.",
      priceKes: 650,
      originalPriceKes: null,
      imageUrl: null,
      images: [] as string[],
      category: "Skincare",
      stock: 60,
      featured: false,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "so-p4",
      storeId: "demo-social",
      name: "Argan Oil Repair Conditioner",
      description: "Restore shine and softness to damaged hair.",
      priceKes: 780,
      originalPriceKes: null,
      imageUrl: null,
      images: [] as string[],
      category: "Hair Care",
      stock: 29,
      featured: false,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "so-p5",
      storeId: "demo-social",
      name: "Rose Water Toning Mist",
      description: "Hydrate and refresh skin throughout the day.",
      priceKes: 550,
      originalPriceKes: 800,
      imageUrl: null,
      images: [] as string[],
      category: "Skincare",
      stock: 72,
      featured: true,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "so-p6",
      storeId: "demo-social",
      name: "Body Butter Trio Pack",
      description: "Vanilla, coconut, and shea body butters.",
      priceKes: 2100,
      originalPriceKes: 2800,
      imageUrl: null,
      images: [] as string[],
      category: "Skincare",
      stock: 15,
      featured: true,
      active: true,
      createdAt: new Date().toISOString(),
    },
  ],
  boutique: [
    {
      id: "bo-p1",
      storeId: "demo-boutique",
      name: "Silk Finish Foundation",
      description: "Full coverage, lightweight formula for all skin tones.",
      priceKes: 2400,
      originalPriceKes: 3200,
      imageUrl: null,
      images: [] as string[],
      category: "Makeup",
      stock: 22,
      featured: true,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "bo-p2",
      storeId: "demo-boutique",
      name: "24H Stay Matte Lipstick",
      description: "Bold, long-lasting color in 12 shades.",
      priceKes: 850,
      originalPriceKes: null,
      imageUrl: null,
      images: [] as string[],
      category: "Makeup",
      stock: 55,
      featured: false,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "bo-p3",
      storeId: "demo-boutique",
      name: "Retinol Night Cream",
      description: "Anti-aging formula that works while you sleep.",
      priceKes: 3200,
      originalPriceKes: 4000,
      imageUrl: null,
      images: [] as string[],
      category: "Skincare",
      stock: 18,
      featured: true,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "bo-p4",
      storeId: "demo-boutique",
      name: "Hyaluronic Acid Serum",
      description: "Deep hydration for plump, youthful skin.",
      priceKes: 1950,
      originalPriceKes: null,
      imageUrl: null,
      images: [] as string[],
      category: "Skincare",
      stock: 34,
      featured: true,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "bo-p5",
      storeId: "demo-boutique",
      name: "Curl Defining Cream",
      description: "Define and moisturize natural curls all day.",
      priceKes: 1200,
      originalPriceKes: 1600,
      imageUrl: null,
      images: [] as string[],
      category: "Hair Care",
      stock: 41,
      featured: false,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "bo-p6",
      storeId: "demo-boutique",
      name: "Scalp Treatment Oil",
      description: "Soothe scalp and promote healthy hair growth.",
      priceKes: 980,
      originalPriceKes: null,
      imageUrl: null,
      images: [] as string[],
      category: "Hair Care",
      stock: 27,
      featured: false,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "bo-p7",
      storeId: "demo-boutique",
      name: "Tailored Linen Blazer",
      description: "Elegant, breathable blazer for any occasion.",
      priceKes: 8500,
      originalPriceKes: 11000,
      imageUrl: null,
      images: [] as string[],
      category: "Fashion",
      stock: 8,
      featured: true,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "bo-p8",
      storeId: "demo-boutique",
      name: "High-Waist Ankara Skirt",
      description: "Vibrant wax print, fully lined, midi length.",
      priceKes: 3800,
      originalPriceKes: null,
      imageUrl: null,
      images: [] as string[],
      category: "Fashion",
      stock: 14,
      featured: true,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "bo-p9",
      storeId: "demo-boutique",
      name: "Matte Bronzing Powder",
      description: "Sun-kissed glow for all skin tones.",
      priceKes: 1400,
      originalPriceKes: 1800,
      imageUrl: null,
      images: [] as string[],
      category: "Makeup",
      stock: 30,
      featured: false,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "bo-p10",
      storeId: "demo-boutique",
      name: "Hydrating Tinted Moisturizer",
      description: "Sheer coverage with SPF 30 protection.",
      priceKes: 1650,
      originalPriceKes: null,
      imageUrl: null,
      images: [] as string[],
      category: "Makeup",
      stock: 25,
      featured: false,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "bo-p11",
      storeId: "demo-boutique",
      name: "Detox Charcoal Shampoo",
      description: "Remove buildup and restore hair's natural balance.",
      priceKes: 890,
      originalPriceKes: null,
      imageUrl: null,
      images: [] as string[],
      category: "Hair Care",
      stock: 48,
      featured: false,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "bo-p12",
      storeId: "demo-boutique",
      name: "Wrap Dress — Floral Print",
      description: "Versatile floral wrap dress, one-size-fits-most.",
      priceKes: 4200,
      originalPriceKes: 5500,
      imageUrl: null,
      images: [] as string[],
      category: "Fashion",
      stock: 10,
      featured: true,
      active: true,
      createdAt: new Date().toISOString(),
    },
  ],
};

export function formatKes(amount: number): string {
  return `KES ${amount.toLocaleString("en-KE")}`;
}

export const KENYA_COUNTIES = [
  "Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika", "Meru",
  "Nyeri", "Machakos", "Kakamega", "Kilifi", "Malindi", "Lamu", "Garissa",
  "Kisii", "Kericho", "Embu", "Isiolo", "Kitale", "Wajir",
];
