// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-vibes/Editorial.tsx": () => import("../components/mockups/homepage-vibes/Editorial.tsx"),
  "./components/mockups/homepage-vibes/NeonPulse.tsx": () => import("../components/mockups/homepage-vibes/NeonPulse.tsx"),
  "./components/mockups/homepage-vibes/SunBaked.tsx": () => import("../components/mockups/homepage-vibes/SunBaked.tsx")
};
